kind: pipeline
name: maven

steps:
  - name: test
    image: docker:5000/king019/alpine
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
trigger:
  branch:
    - master
  event:
    - push

