kind: pipeline
name: frame

steps:
  - name: install
    image: registry.cn-beijing.aliyuncs.com/king019/alpine
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
    commands:
      - mvn install -Dmaven.test.skip=true
  - name: version
    image: registry.cn-beijing.aliyuncs.com/king019/alpine
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
    commands:
      - mvn versions:display-property-updates
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2