kind: pipeline
name: frame

steps:
  - name: install
    image: king019/alpine
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
    commands:
      - date
      - mvn install -DskipTests=true  -B -V
      - mvn versions:display-property-updates
  - name: version
    image: king019/alpine
    privileged: true
    volumes:
      - name: maven
        path: /root/.m2
    commands:
      - mvn versions:display-property-updates
volumes:
  - name: maven
    host:
      path: /opt/soft/docker/data/maven/m2